services:
  - type: web
    name: bosanski-api
    runtime: node
    plan: free
    region: frankfurt
    rootDir: apps/api
    buildCommand: NPM_CONFIG_PRODUCTION=false npm install --workspaces=false && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npm run start:prod
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: APP_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: API_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-flash-lite-latest
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false
      - key: TURNSTILE_ENABLED
        value: "false"
      - key: SEED_ADMIN_EMAIL
        value: admin@bosanski.local
      - key: SEED_ADMIN_PASSWORD
        value: Admin123!
      - key: SEED_ADMIN_NAME
        value: Super Admin
